# make        check the syntax (node --check); JavaScript has nothing to build
# make run    run hello.js with Node
# make clean  nothing to remove

build:
	node --check hello.js && echo "hello.js: syntax is fine"

run:
	node hello.js


clean:

.PHONY: build run clean
