# make        nothing to build: Forth compiles each word as it reads the file
# make run    run it with gforth
# make clean  nothing to remove

build:
	@echo "nothing to build: gforth compiles words.fs as it reads it (make run)"

run:
	gforth words.fs


clean:

.PHONY: build run clean
