;;; office-ui-visual.el --- Hidden display exercise -*- lexical-binding: t; -*-
(load (expand-file-name "office-ui.el" (file-name-directory load-file-name)) nil t)
(setq vikix-office-interval 60)
(let ((data (copy-tree (office-test-data '("attention" "working" "parked" "finished")))))
  (cl-mapc (lambda (row title group)
             (setf (alist-get 'title row) title (alist-get 'group row) group))
           (alist-get 'desks data)
           '("Build the first version of The Office" "Fix the Wi-Fi picker" "Continue the chapter draft" "Keep handoffs between sessions")
           '("Needs you" "Working" "Parked" "Finished"))
  (setf (alist-get 'agents (nth 1 (alist-get 'desks data)))
        '(((agent . "claude") (pid . 456) (window . "2") (workspace . "4") (doing . "working"))))
  (let ((row (car (alist-get 'desks data))))
    (setf (alist-get 'task row) '((text . "Help Vid see what needs attention, move between agents, and continue unfinished work.") (by . "user") (at . 1791300000))
          (alist-get 'handoff row) '((status . ((value . "review") (by . "codex 123") (at . 1791300120)))
                                    (summary . ((text . "Built the task overview and navigation. Kept conversations in the existing terminals and reused the handoff backend.") (by . "codex 123") (at . 1791300120)))
                                    (next . ((text . "Review the Office on the hidden display, then release.") (by . "codex 123") (at . 1791300120))))
          (alist-get 'now row) '((commit . "abc1234") (branch . "office-ui") (dirty . 0) (at . 1791300120))
          (alist-get 'checks row) '(((name . "tests/run.sh office-ui") (ok . t) (by . "codex 123") (at . 1791300000) (commit . "abc1234") (dirty . 0) (freshness . "fresh")))))
  (setq vikix-office-command
        (list "python3" "-c" (concat "print(" (json-encode (json-encode data)) ")"))))
(load-theme 'modus-vivendi t)
(vikix-office-open)
(run-at-time
 1 nil
 (lambda ()
   (condition-case err
       (let* ((frame (cl-find-if (lambda (f) (frame-parameter f 'vikix-office-buffer)) (frame-list)))
              (buffer (frame-parameter frame 'vikix-office-buffer)))
         (select-frame-set-input-focus frame)
         (with-current-buffer buffer
           (unless (equal vikix-office--selected "attention") (error "No asynchronous snapshot"))
           (let* ((detail vikix-office--detail) (window (get-buffer-window detail frame))
                  (process nil))
             (select-window window)
             (goto-char (point-min)) (forward-line 9)
             (let ((point (point)) (start (window-start window)))
               (with-current-buffer buffer (vikix-office--render))
               (unless (and (eq (selected-window) window) (= point (point)) (= start (window-start window)))
                 (error "Refresh changed detail focus or scroll")))
             (redisplay t)
             (when (and (getenv "VIKIX_OFFICE_SCREENSHOT") (executable-find "import"))
               (call-process "import" nil nil nil "-window" "root" (getenv "VIKIX_OFFICE_SCREENSHOT")))
             (with-current-buffer buffer
               (let ((vikix-office-command '("python3" "-c" "import time; time.sleep(20)")))
                 (vikix-office-refresh)
                 (setq process vikix-office--process)))
             (delete-frame frame)
             (when (or (buffer-live-p buffer) (buffer-live-p detail) (process-live-p process))
               (error "Closing frame left Office work running"))))
         (write-region "Office visual: rendered, focus preserved, frame cleanup passed\n" nil (expand-file-name "visual-result" (getenv "HOME")) nil 'silent)
         (kill-emacs 0))
     (error (write-region (format "Office visual failed: %S\n" err) nil (expand-file-name "visual-result" (getenv "HOME")) nil 'silent) (kill-emacs 1)))))
