# make        check the syntax (ruby -c); Ruby has nothing to build
# make run    run blocks.rb
# make clean  nothing to remove

build:
	ruby -c blocks.rb

run:
	ruby blocks.rb


clean:

.PHONY: build run clean
