# make        check the syntax (node --check); JavaScript has nothing to build
# make run    run server.js with Node
# make clean  nothing to remove

build:
	node --check server.js && echo "server.js: syntax is fine"

run:
	node server.js


clean:

.PHONY: build run clean
