# make        check the syntax (ruby -c); Ruby has nothing to build
# make run    run hello.rb
# make clean  nothing to remove

build:
	ruby -c hello.rb

run:
	ruby hello.rb


clean:

.PHONY: build run clean
